FROM eclipse-temurin:21-alpine
EXPOSE 9015
RUN mkdir /app
COPY --chown=gradle:gradle ./build/libs/service.jar /app/weather-service.jar
ENTRYPOINT ["java","-Duser.timezone=UTC","-jar","/app/weather-service.jar"]
CMD []